### ISSUE TITLE
Cadastro, edição e exclusão de produtos

### ISSUE THREAD

**Issue by ThiagoGalhardo** [tatmorenno/beacademy-devstart-jade#29]

**Comment by fabinho-oc** [comment]
Create method list product admin
![listProductAdmin_v1](https://user-images.githubusercontent.com/83736799/180622984-d848bed0-68d1-4055-9f45-89c0c5d7e566.JPG)
![listedProductAdmin_v1](https://user-images.githubusercontent.com/83736799/180622987-85ed425f-9b96-4b12-a351-39fd8833aa8f.JPG)
